# Scrubbing and Cleaning Data - Lab

## Introduction

In the previous labs, you joined the data from our separate files into a single DataFrame.  In this lab, you'll scrub the data to get it ready for exploration and modeling!

## Objectives

You will be able to:

* Cast columns to the appropriate data types
* Identify and deal with null values appropriately
* Remove unnecessary columns
* Understand how to normalize data


## Getting Started

You'll find the resulting dataset from our work in the _Obtaining Data_ Lab stored within the file `walmart_data_not_cleaned.csv`.  

In the cells below:

* Import pandas and set the standard alias
* Import numpy and set the standard alias
* Import matplotlib.pyplot and set the standard alias
* Import seaborn and set the alias `sns` (this is the standard alias for seaborn)
* Use the ipython magic command to set all matplotlib visualizations to display inline in the notebook
* Load the dataset stored in the .csv file into a DataFrame using pandas
* Inspect the head of the DataFrame to ensure everything loaded correctly

In [7]:
# Import statements go here
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
%matplotlib inline
import seaborn as sns

In [8]:
!ls

CONTRIBUTING.md  index.ipynb  Lego_data_merged.csv  LICENSE.md	README.md

In [9]:
# Now, load in the dataset and inspect the head to make sure everything loaded correctly
df = pd.read_csv('Lego_data_merged.csv')
df.head()

,prod_id,ages,piece_count,set_name,prod_desc,prod_long_desc,theme_name,country,list_price,num_reviews,play_star_rating,review_difficulty,star_rating,val_star_rating
0,75823,6-12,277,Bird Island Egg Heist,Catapult into action and take back the eggs fr...,Use the staircase catapult to launch Red into ...,Angry Birds™,US,$29.99,2.0,4.0,Average,4.5,4.0
1,75822,6-12,168,Piggy Plane Attack,Launch a flying attack and rescue the eggs fro...,Pilot Pig has taken off from Bird Island with ...,Angry Birds™,US,$19.99,2.0,4.0,Easy,5.0,4.0
2,75821,6-12,74,Piggy Car Escape,Chase the piggy with lightning-fast Chuck and ...,Pitch speedy bird Chuck against the Piggy Car....,Angry Birds™,US,$12.99,11.0,4.3,Easy,4.3,4.1
3,21030,12+,1032,United States Capitol Building,Explore the architecture of the United States ...,Discover the architectural secrets of the icon...,Architecture,US,$99.99,23.0,3.6,Average,4.6,4.3
4,21035,12+,744,Solomon R. Guggenheim Museum®,Recreate the Solomon R. Guggenheim Museum® wit...,Discover the architectural secrets of Frank Ll...,Architecture,US,$79.99,14.0,3.2,Challenging,4.6,4.1

## Starting our Data Cleaning

To start, you'll deal with the most obvious issue: data features with the wrong data encoding.

### Checking Data Types

In the cell below, use the appropriate method to check the data type of each column.

In [10]:
#Your code here
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10870 entries, 0 to 10869
Data columns (total 14 columns):
prod_id              10870 non-null int64
ages                 10870 non-null object
piece_count          10870 non-null int64
set_name             10870 non-null object
prod_desc            10512 non-null object
prod_long_desc       10870 non-null object
theme_name           10870 non-null object
country              10870 non-null object
list_price           10870 non-null object
num_reviews          9449 non-null float64
play_star_rating     9321 non-null float64
review_difficulty    9104 non-null object
star_rating          9449 non-null float64
val_star_rating      9301 non-null float64
dtypes: float64(4), int64(2), object(8)
memory usage: 1.2+ MB

Now, investigate some of the unique values inside of the `list_price` column.

In [11]:
#Your code here
df.list_price.unique()[:10]

array(['$29.99', '$19.99', '$12.99', '$99.99', '$79.99', '$59.99',
       '$49.99', '$39.99', '$34.99', '$159.99'], dtype=object)

### Numerical Data Stored as Strings

A common issue to check for at this stage is numeric columns that have accidentally been encoded as strings. For example, you should notice that the `list_price` column above is currently formatted as a string and contains a proceeding '$'. Remove this and convert the remaining number to a `float` so that you can later model this value. After all, your primary task is to generate model to predict the price.

> Note: While the data spans a multitude of countries, assume for now that all prices have been standardized to USD.

In [12]:
#Your code here
df['list_price'] = df.list_price.map(lambda x: float(x[1:]))

In [13]:
df.list_price.unique()[:10], type(df.list_price[1])

(array([ 29.99,  19.99,  12.99,  99.99,  79.99,  59.99,  49.99,  39.99,
         34.99, 159.99]), numpy.float64)

### Detecting and Dealing With Null Values

Next, it's time to check for null values. How to deal with the null values will be determined by the columns containing them, and how many null values exist in each.  
 
In the cell below, get a count of how many null values exist in each column in the DataFrame.

In [14]:
#Your code here
df.isna().sum()

prod_id                 0
ages                    0
piece_count             0
set_name                0
prod_desc             358
prod_long_desc          0
theme_name              0
country                 0
list_price              0
num_reviews          1421
play_star_rating     1549
review_difficulty    1766
star_rating          1421
val_star_rating      1569
dtype: int64

Now, get some descriptive statistics for each of the columns. You want to see where the minimum and maximum values lie.

In [15]:
#Your code here
df.describe()

,prod_id,piece_count,list_price,num_reviews,play_star_rating,star_rating,val_star_rating
count,1.087000e+04,10870.000000,10870.000000,9449.000000,9321.000000,9449.000000,9301.000000
mean,6.181634e+04,503.936431,67.309137,17.813737,4.355413,4.510319,4.214439
std,1.736390e+05,831.209318,94.669414,38.166693,0.617272,0.516463,0.670906
min,6.300000e+02,1.000000,2.272400,1.000000,1.000000,1.800000,1.000000
25%,2.112300e+04,97.000000,21.899000,2.000000,4.000000,4.300000,4.000000
50%,4.207350e+04,223.000000,36.587800,6.000000,4.500000,4.600000,4.300000
75%,7.124800e+04,556.000000,73.187800,14.000000,4.800000,5.000000,4.700000
max,2.000431e+06,7541.000000,1104.870000,367.000000,5.000000,5.000000,5.000000

Now that you have a bit more of a understanding of each of these features you can now make an informed decision about the best strategy for dealing with the various null values. 

Some common strategies for filling null values include:
* Using the mean of the feature
* Using the median of the feature
* Inserting a random value from a normal distribution with the mean and std of the feature
* Binning

Given that most of the features with null values concern user reviews of the lego set, it is reasonable to wonder whether there is strong correlation between these features in the first place. Before proceeding, take a minute to investigate this hypothesis.

In [16]:
#Investigate whether multicollinearity exists between the review features 
#(num_reviews, play_star_rating, star_rating, val_star_rating)
df.corr()

,prod_id,piece_count,list_price,num_reviews,play_star_rating,star_rating,val_star_rating
prod_id,1.000000,0.221692,0.394525,-0.044658,-0.008234,-0.062264,-0.083703
piece_count,0.221692,1.000000,0.865094,0.542208,-0.007952,0.067610,0.067296
list_price,0.394525,0.865094,1.000000,0.437724,-0.000685,-0.006497,-0.055899
num_reviews,-0.044658,0.542208,0.437724,1.000000,-0.060884,0.004541,0.026664
play_star_rating,-0.008234,-0.007952,-0.000685,-0.060884,1.000000,0.619246,0.484341
star_rating,-0.062264,0.067610,-0.006497,0.004541,0.619246,1.000000,0.731538
val_star_rating,-0.083703,0.067296,-0.055899,0.026664,0.484341,0.731538,1.000000

Note that there is substantial correlation between the `play_star_rating`, `star_rating` and `val_star_rating`. While this could lead to multicollinearity in your eventual regression model, it is too early to clearly determine this at this point. Remember that multicollinearity is a relationship between 3 or more variables while correlation simply investigates the relationship between two variables.

Additionally, these relationships provide an alternative method for imputing missing values: since they appear to be correlated, you could use these features to help impute missing values in the others features. For example, if you are missing the star_rating for a particular row but have the val_star_rating for that same entry, it seems reasonable to assume that it is a good estimate for the missing star_rating value as they are highly correlated. That said, doing so does come with risks; indeed you would be further increasing the correlation between these features which could further provoke multicollinearity in the final model.

Investigate if you could use one of the other star rating features when one is missing. How many rows have one of `play_star_rating`, `star_rating` and `val_star_rating` missing, but not all three.

In [19]:
#Your code here
missing_1 = df[df['play_star_rating'].isna() | df['star_rating'].isna() | df['val_star_rating'].isna()]
missing_3 = df[df['play_star_rating'].isna() & df['star_rating'].isna() & df['val_star_rating'].isna()]
df1 = missing_1.copy()
df2 = missing_3.copy()
missing_1_not_3 = pd.concat([df1,df2]).drop_duplicates(keep=False)

In [20]:
missing_1_not_3

,prod_id,ages,piece_count,set_name,prod_desc,prod_long_desc,theme_name,country,list_price,num_reviews,play_star_rating,review_difficulty,star_rating,val_star_rating
22,41607,10+,136,Gamora,Master the skills of a green-skinned assassin ...,This Gamora LEGO® BrickHeadz construction char...,BrickHeadz,US,9.9900,1.0,NaN,NaN,5.0,NaN
94,60171,5-12,88,Mountain Fugitives,Arrest the crooks and recover the hidden loot!,Pick up your badge and join the LEGO® City Mou...,City,US,9.9900,2.0,NaN,NaN,5.0,NaN
258,10879,2-5,24,Gentle Giants Petting Zoo,See the baby dinosaurs at the Jurassic World G...,Little dinosaur fans will love to create endle...,DUPLO®,US,19.9900,1.0,NaN,NaN,5.0,NaN
325,41188,8-12,695,Breakout from the Goblin King's Fortress,Stop the Goblin King’s evil plan and rescue Em...,Join the exciting adventures in Elvendale as E...,Elves,US,69.9900,1.0,NaN,NaN,5.0,NaN
402,10740,4-7,110,Fire Patrol Suitcase,Help the firefighters battle the blaze!,Be prepared for a LEGO® City emergency whereve...,Juniors,US,19.9900,1.0,NaN,Easy,4.0,NaN
415,75929,7-12,577,Carnotaurus Gyrosphere Escape,Escape from the rampaging Carnotaurus!,Flee the flying lava rocks and a deadly dinosa...,Carnotaurus Gyrosphere Escape,US,79.9900,1.0,NaN,NaN,5.0,NaN
458,45503,10-21,1,EV3 Medium Servo Motor,NaN,The EV3 Medium Servo Motor is great for lower-...,MINDSTORMS®,US,21.9900,1.0,5.0,Easy,5.0,NaN
500,70354,8-14,393,Axl's Rumble Maker,Keep trouble at bay with Axl’s 3-in-1 Rumble M...,Drive the Rogul out of Knighton with the 3-in-...,NEXO KNIGHTS™,US,39.9900,1.0,NaN,NaN,5.0,NaN
741,41607,10+,136,Gamora,Master the skills of a green-skinned assassin ...,This Gamora LEGO® BrickHeadz construction char...,BrickHeadz,AU,12.1524,1.0,NaN,NaN,5.0,NaN
798,60171,5-12,88,Mountain Fugitives,Arrest the crooks and recover the hidden loot!,Pick up your badge and join the LEGO® City Mou...,City,AU,12.1524,2.0,NaN,NaN,5.0,NaN
907,10879,2-5,24,Gentle Giants Petting Zoo,See the baby dinosaurs at the Jurassic World G...,Little dinosaur fans will love to create endle...,DUPLO®,AU,22.7924,1.0,NaN,NaN,5.0,NaN
962,41188,8-12,695,Breakout from the Goblin King's Fortress,Stop the Goblin King’s evil plan and rescue Em...,Join the exciting adventures in Elvendale as E...,Elves,AU,75.9924,1.0,NaN,NaN,5.0,NaN
1010,10740,4-7,110,Fire Patrol Suitcase,Help the firefighters battle the blaze!,Be prepared for a LEGO® City emergency whereve...,Juniors,AU,30.3924,1.0,NaN,Easy,4.0,NaN
1019,75929,7-12,577,Carnotaurus Gyrosphere Escape,Escape from the rampaging Carnotaurus!,Flee the flying lava rocks and a deadly dinosa...,Carnotaurus Gyrosphere Escape,AU,91.1924,1.0,NaN,NaN,5.0,NaN
1055,45503,10-21,1,EV3 Medium Servo Motor,NaN,The EV3 Medium Servo Motor is great for lower-...,MINDSTORMS®,AU,22.7924,1.0,5.0,Easy,5.0,NaN
1247,41607,10+,136,Gamora,Master the skills of a green-skinned assassin ...,This Gamora LEGO® BrickHeadz construction char...,BrickHeadz,AT,12.1878,1.0,NaN,NaN,5.0,NaN
1304,60171,5-12,88,Mountain Fugitives,Arrest the crooks and recover the hidden loot!,Pick up your badge and join the LEGO® City Mou...,City,AT,12.1878,2.0,NaN,NaN,5.0,NaN
1417,10879,2-5,24,Gentle Giants Petting Zoo,See the baby dinosaurs at the Jurassic World G...,Little dinosaur fans will love to create endle...,DUPLO®,AT,24.3878,1.0,NaN,NaN,5.0,NaN
1472,41188,8-12,695,Breakout from the Goblin King's Fortress,Stop the Goblin King’s evil plan and rescue Em...,Join the exciting adventures in Elvendale as E...,Elves,AT,85.3878,1.0,NaN,NaN,5.0,NaN
1523,10740,4-7,110,Fire Patrol Suitcase,Help the firefighters battle the blaze!,Be prepared for a LEGO® City emergency whereve...,Juniors,AT,24.3878,1.0,NaN,Easy,4.0,NaN
1529,75929,7-12,577,Carnotaurus Gyrosphere Escape,Escape from the rampaging Carnotaurus!,Flee the flying lava rocks and a deadly dinosa...,Carnotaurus Gyrosphere Escape,AT,97.5878,1.0,NaN,NaN,5.0,NaN
1565,45503,10-21,1,EV3 Medium Servo Motor,NaN,The EV3 Medium Servo Motor is great for lower-...,MINDSTORMS®,AT,30.4878,1.0,5.0,Easy,5.0,NaN
1756,41607,10+,136,Gamora,Master the skills of a green-skinned assassin ...,This Gamora LEGO® BrickHeadz construction char...,BrickHeadz,BE,12.1878,1.0,NaN,NaN,5.0,NaN
1813,60171,5-12,88,Mountain Fugitives,Arrest the crooks and recover the hidden loot!,Pick up your badge and join the LEGO® City Mou...,City,BE,12.1878,2.0,NaN,NaN,5.0,NaN
1919,10879,2-5,24,Gentle Giants Petting Zoo,See the baby dinosaurs at the Jurassic World G...,Little dinosaur fans will love to create endle...,DUPLO®,BE,24.3878,1.0,NaN,NaN,5.0,NaN
1973,41188,8-12,695,Breakout from the Goblin King's Fortress,Stop the Goblin King’s evil plan and rescue Em...,Join the exciting adventures in Elvendale as E...,Elves,BE,97.5878,1.0,NaN,NaN,5.0,NaN
2023,10740,4-7,110,Fire Patrol Suitcase,Help the firefighters battle the blaze!,Be prepared for a LEGO® City emergency whereve...,Juniors,BE,24.3878,1.0,NaN,Easy,4.0,NaN
2030,75929,7-12,577,Carnotaurus Gyrosphere Escape,Escape from the rampaging Carnotaurus!,Flee the flying lava rocks and a deadly dinosa...,Carnotaurus Gyrosphere Escape,BE,109.7878,1.0,NaN,NaN,5.0,NaN
2260,41607,10+,136,Gamora,Master the skills of a green-skinned assassin ...,This Gamora LEGO® BrickHeadz construction char...,BrickHeadz,CA,10.1322,1.0,NaN,NaN,5.0,NaN
2332,60171,5-12,88,Mountain Fugitives,Arrest the crooks and recover the hidden loot!,Pick up your badge and join the LEGO® City Mou...,City,CA,10.1322,2.0,NaN,NaN,5.0,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8692,75929,7-12,577,Carnotaurus Gyrosphere Escape,Escape from the rampaging Carnotaurus!,Flee the flying lava rocks and a deadly dinosa...,Carnotaurus Gyrosphere Escape,NO,116.8700,1.0,NaN,NaN,5.0,NaN
8728,45503,10-21,1,EV3 Medium Servo Motor,NaN,The EV3 Medium Servo Motor is great for lower-...,MINDSTORMS®,NO,38.8700,1.0,5.0,Easy,5.0,NaN
8920,41607,10+,136,Gamora,Master the skills of a green-skinned assassin ...,This Gamora LEGO® BrickHeadz construction char...,BrickHeadz,NL,12.1878,1.0,NaN,NaN,5.0,NaN
8977,60171,5-12,88,Mountain Fugitives,Arrest the crooks and recover the hidden loot!,Pick up your badge and join the LEGO® City Mou...,City,NL,12.1878,2.0,NaN,NaN,5.0,NaN
9090,10879,2-5,24,Gentle Giants Petting Zoo,See the baby dinosaurs at the Jurassic World G...,Little dinosaur fans will love to create endle...,DUPLO®,NL,24.3878,1.0,NaN,NaN,5.0,NaN
9145,41188,8-12,695,Breakout from the Goblin King's Fortress,Stop the Goblin King’s evil plan and rescue Em...,Join the exciting adventures in Elvendale as E...,Elves,NL,97.5878,1.0,NaN,NaN,5.0,NaN
9194,10740,4-7,110,Fire Patrol Suitcase,Help the firefighters battle the blaze!,Be prepared for a LEGO® City emergency whereve...,Juniors,NL,24.3878,1.0,NaN,Easy,4.0,NaN
9202,75929,7-12,577,Carnotaurus Gyrosphere Escape,Escape from the rampaging Carnotaurus!,Flee the flying lava rocks and a deadly dinosa...,Carnotaurus Gyrosphere Escape,NL,109.7878,1.0,NaN,NaN,5.0,NaN
9238,45503,10-21,1,EV3 Medium Servo Motor,NaN,The EV3 Medium Servo Motor is great for lower-...,MINDSTORMS®,NL,32.9278,1.0,5.0,Easy,5.0,NaN
9430,41607,10+,136,Gamora,Master the skills of a green-skinned assassin ...,This Gamora LEGO® BrickHeadz construction char...,BrickHeadz,NZ,14.1929,1.0,NaN,NaN,5.0,NaN
9487,60171,5-12,88,Mountain Fugitives,Arrest the crooks and recover the hidden loot!,Pick up your badge and join the LEGO® City Mou...,City,NZ,14.1929,2.0,NaN,NaN,5.0,NaN
9596,10879,2-5,24,Gentle Giants Petting Zoo,See the baby dinosaurs at the Jurassic World G...,Little dinosaur fans will love to create endle...,DUPLO®,NZ,24.8429,1.0,NaN,NaN,5.0,NaN
9651,41188,8-12,695,Breakout from the Goblin King's Fortress,Stop the Goblin King’s evil plan and rescue Em...,Join the exciting adventures in Elvendale as E...,Elves,NZ,78.0929,1.0,NaN,NaN,5.0,NaN
9699,10740,4-7,110,Fire Patrol Suitcase,Help the firefighters battle the blaze!,Be prepared for a LEGO® City emergency whereve...,Juniors,NZ,31.9429,1.0,NaN,Easy,4.0,NaN
9708,75929,7-12,577,Carnotaurus Gyrosphere Escape,Escape from the rampaging Carnotaurus!,Flee the flying lava rocks and a deadly dinosa...,Carnotaurus Gyrosphere Escape,NZ,106.4929,1.0,NaN,NaN,5.0,NaN
9744,45503,10-21,1,EV3 Medium Servo Motor,NaN,The EV3 Medium Servo Motor is great for lower-...,MINDSTORMS®,NZ,17.7429,1.0,5.0,Easy,5.0,NaN
9933,41607,10+,136,Gamora,Master the skills of a green-skinned assassin ...,This Gamora LEGO® BrickHeadz construction char...,BrickHeadz,PL,13.0471,1.0,NaN,NaN,5.0,NaN
9986,60171,5-12,88,Mountain Fugitives,Arrest the crooks and recover the hidden loot!,Pick up your badge and join the LEGO® City Mou...,City,PL,12.4671,2.0,NaN,NaN,5.0,NaN
10080,10879,2-5,24,Gentle Giants Petting Zoo,See the baby dinosaurs at the Jurassic World G...,Little dinosaur fans will love to create endle...,DUPLO®,PL,26.0971,1.0,NaN,NaN,5.0,NaN
10135,41188,8-12,695,Breakout from the Goblin King's Fortress,Stop the Goblin King’s evil plan and rescue Em...,Join the exciting adventures in Elvendale as E...,Elves,PL,89.8971,1.0,NaN,NaN,5.0,NaN
10174,10740,4-7,110,Fire Patrol Suitcase,Help the firefighters battle the blaze!,Be prepared for a LEGO® City emergency whereve...,Juniors,PL,26.0971,1.0,NaN,Easy,4.0,NaN
10182,75929,7-12,577,Carnotaurus Gyrosphere Escape,Escape from the rampaging Carnotaurus!,Flee the flying lava rocks and a deadly dinosa...,Carnotaurus Gyrosphere Escape,PL,110.1971,1.0,NaN,NaN,5.0,NaN
10218,45503,10-21,1,EV3 Medium Servo Motor,NaN,The EV3 Medium Servo Motor is great for lower-...,MINDSTORMS®,PL,37.6971,1.0,5.0,Easy,5.0,NaN
10403,41607,10+,136,Gamora,Master the skills of a green-skinned assassin ...,This Gamora LEGO® BrickHeadz construction char...,BrickHeadz,PT,12.1878,1.0,NaN,NaN,5.0,NaN
10460,60171,5-12,88,Mountain Fugitives,Arrest the crooks and recover the hidden loot!,Pick up your badge and join the LEGO® City Mou...,City,PT,12.1878,2.0,NaN,NaN,5.0,NaN
10550,10879,2-5,24,Gentle Giants Petting Zoo,See the baby dinosaurs at the Jurassic World G...,Little dinosaur fans will love to create endle...,DUPLO®,PT,24.3878,1.0,NaN,NaN,5.0,NaN
10605,41188,8-12,695,Breakout from the Goblin King's Fortress,Stop the Goblin King’s evil plan and rescue Em...,Join the exciting adventures in Elvendale as E...,Elves,PT,97.5878,1.0,NaN,NaN,5.0,NaN
10656,10740,4-7,110,Fire Patrol Suitcase,Help the firefighters battle the blaze!,Be prepared for a LEGO® City emergency whereve...,Juniors,PT,24.3878,1.0,NaN,Easy,4.0,NaN
10662,75929,7-12,577,Carnotaurus Gyrosphere Escape,Escape from the rampaging Carnotaurus!,Flee the flying lava rocks and a deadly dinosa...,Carnotaurus Gyrosphere Escape,PT,103.6878,1.0,NaN,NaN,5.0,NaN
10697,45503,10-21,1,EV3 Medium Servo Motor,NaN,The EV3 Medium Servo Motor is great for lower-...,MINDSTORMS®,PT,30.4878,1.0,5.0,Easy,5.0,NaN

Well, it seems like when one is missing, the other two are also apt to be missing. While this has been a bit of an extended investigation, simply go ahead and fill the missing values with that features median.  

Fill in the missing `review_difficulty` values with 'unknown'.

In [ ]:
#Your code here
df['play_star_rating'].fillna(value=df.play_star_rating.median(), inplace=True)
df['star_rating'].fillna(value=df.star_rating.median(), inplace=True)
df['val_star_rating'].fillna(value=df.val_star_rating.median(), inplace=True)
df['num_reviews'].fillna(value=df.num_reviews.median(), inplace=True)
df['review_difficulty'].fillna(value='unknown', inplace=True)

In [29]:
df.isna().sum()

prod_id                0
ages                   0
piece_count            0
set_name               0
prod_desc            358
prod_long_desc         0
theme_name             0
country                0
list_price             0
num_reviews            0
play_star_rating       0
review_difficulty      0
star_rating            0
val_star_rating        0
dtype: int64

## Normalizing the Data

Now, you'll need to convert all of our numeric columns to the same scale by **_normalizing_** our dataset.  Recall that you normalize a dataset by converting each numeric value to it's corresponding z-score for the column, which is obtained by subtracting the column's mean and then dividing by the column's standard deviation for every value. 


In the cell below:

* Normalize the numeric X features by subtracting the column mean and dividing by the column standard deviation. 
(Don't bother to normalize the list_price as this is the feature you will be predicting.)

In [30]:
#Your code here
def norm_col(col):
    return (col - col.mean())/col.std()

for col in ['piece_count', 'num_reviews', 'play_star_rating', 'star_rating', 'val_star_rating']:
    df[col] = norm_col(df[col])
    
df.describe()

,prod_id,piece_count,list_price,num_reviews,play_star_rating,star_rating,val_star_rating
count,1.087000e+04,1.087000e+04,10870.000000,1.087000e+04,1.087000e+04,1.087000e+04,1.087000e+04
mean,6.181634e+04,8.497751e-18,67.309137,-2.287856e-18,1.034111e-15,-1.653139e-15,2.881882e-16
std,1.736390e+05,1.000000e+00,94.669414,1.000000e+00,1.000000e+00,1.000000e+00,1.000000e+00
min,6.300000e+02,-6.050659e-01,2.272400,-4.264402e-01,-5.883334e+00,-5.641909e+00,-5.193413e+00
25%,2.112300e+04,-4.895715e-01,21.899000,-3.705846e-01,-4.810100e-01,-4.602216e-01,-3.650101e-01
50%,4.207350e+04,-3.379852e-01,36.587800,-2.868011e-01,2.160641e-01,1.615809e-01,1.178302e-01
75%,7.124800e+04,6.263593e-02,73.187800,-1.192341e-01,5.646012e-01,7.833834e-01,6.006705e-01
max,2.000431e+06,8.466055e+00,1104.870000,9.795146e+00,1.087407e+00,9.906510e-01,1.244458e+00

## Saving Your Results

While you'll once again practice one-hot encoding as you would to preprocess data before fitting a model, saving such a reperesentation of the data will eat up additional disk space. After all, a categorical variable with 10 bins will be transformed to 10 seperate features when passed through `pd.get_dummies()`. As such, while the further practice is worthwhile, save your DataFrame as is for now.

In [31]:
#Your code here
df.to_csv('toto.csv')

## One-Hot Encoding Categorical Columns

As a final step, you'll need to deal with the categorical columns by **_one-hot encoding_** them into binary variables via the `pd.get_dummies()` method.  

When doing this, you should also subset to appropriate features. If you were to simply pass the entire DataFrame to the `pd.get_dummies()` method as it stands now, then you would end up with unique features for every single product description! (Presumably the descriptions are unique.) As such, you should first subset to the numeric features that you will eventually use in a model along with categorical variables that are not unique.

In the cell below, subset to the appropriate predictive features and then use the [`pd.get_dummies()`](https://pandas.pydata.org/pandas-docs/stable/generated/pandas.get_dummies.html) to one-hot encode the dataset.

In [33]:
df.info()

dtype('O')

In [ ]:
#Your code here
feats = ['ages', 'piece_count', 'theme_name', 'country', 'list_price', 'num_reviews',
         'play_star_rating', 'review_difficulty', 'star_rating', 'val_star_rating']
#Don't include prod_id, set_name, prod_desc, or prod_long_desc; they are too unique
df = df[feats]
df = pd.get_dummies(df)

That's it! You've now successfully scrubbed your dataset--you're now ready for data exploration and modeling!

## Summary

In this lesson, you learned gain practice with data cleaning by:

* Casting columns to the appropriate data types
* Identifying and deal with null values appropriately
* Removing unnecessary columns
* Checking for and deal with multicollinearity
* Normalizing your data